configurations:
  - acls:
  - ospf:
  - eigrp:
  - static routes:
  - static default routes:
  - vlan trunking:
  - vlan access ports:
  - port security:
  - qos:
  - etherchannel:
  - dhcpv4:
  - dhcpv6:


# stp, etherchannel?, l3 inter-vlan routing, ospf,
# acl, nat, dhcpv4, dns
standard_lan:

  common_config:
    domain_name:
    vty:
    console:
    default_gateway: 
    motd:

  devices:
    - device: router
      name: 01_edge_router 

      services:
        - acl:
        - ospf:
        - nat:
        - dhcpv4:

      interfaces:
        - interface: g0/0
          address: 88.88.88.1
          mask: 255.255.255.248
          nat: outside

        - interface: g0/1
          address: 10.0.0.1
          mask: 255.255.0.0
          nat: inside

      ospf:
        - process_id: 1
          networks:
            - network: 88.88.88.0
              wildcard: 0.0.0.7
              area: 0

      acls:
        - acl_type: standard
          name: LAN_OVERLOAD
          aces:
            - ace: 10
              allow: permit
              source:
                address: 10.5.1.0
                wildcard: 0.0.255.255

            - ace: 50
              allow: deny
              source:
                address: 0.0.0.0
                wildcard: 255.255.255.255

      nat:
        - 


    - device: switch
      name: core_switch_01

      services:
        - inter-vlan routing:
        - svis:
        - routed port:

      vlans:
        - vlan_id: 2
          name: native

        - vlan_id: 5
          name: admin

        - vlan_id: 6
          name: network

        - vlan_id: 10
          name: servers

        - vlan_id: 20
          name: users

      interfaces:
        - interface: g1/0/1
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10, 20]
          description: link to 01_closet_a

        - interface: g1/0/24
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10, 20]
          description: link to 01_edge_router

        - interface: vlan 5
          mode: svi
          address: 10.6.0.1
          mask: 255.255.0.0

    - device: switch
      name: 01_closet_a

      services:
        - svi:
        - vlan trunking:
        - spanning tree root:
          
      vlans:
        - vlan_id: 2
          name: native

        - vlan_id: 5
          name: admin

        - vlan_id: 6
          name: network

        - vlan_id: 10
          name: servers

        - vlan_id: 20
          name: users

      interfaces:
        - interface: f0/24
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10, 20]
          description: link to 01_closet_b

        - interface: f0/23
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10, 20]
          description: link to 01_closet_c

        - interface: vlan 5
          mode: svi
          address: 10.6.0.2
          mask: 255.255.0.0

