configurations:
  - acls:
  - ospf:
  - eigrp:
  - static routes:
  - static default routes:
  - vlan trunking:
  - vlan access ports:
  - port security:
  - qos:
  - etherchannel:
  - dhcpv4:
  - dhcpv6:


# stp, etherchannel?, l3 inter-vlan routing, ospf,
# acl, nat, dhcpv4, dns
standard_lan:

  common_config:
    domain_name:
    vty:
    console:
    default_gateway: 

  devices:
    - device: router
      name: 01_edge_router 

      services:
        - acl:
        - ospf:
        - nat:
        - dhcpv4:

      interfaces:
        - interface: g0/0
          address: 88.88.88.1
          mask: 255.255.255.248
          nat: outside

        - interface: g0/1
          address: 10.0.0.1
          mask: 255.255.0.0
          nat: inside

    - device: switch
      name: core_switch_01

      services:
        - inter-vlan routing:
        - svis:
        - routed port:

      vlans:
        - vlan_id: 2
          name: native

        - vlan_id: 5
          name: admin

        - vlan_id: 6
          name: network

        - vlan_id: 10
          name: servers

      interfaces:
        - interface: g1/0/1
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10]
          description: link to 01_closet_a

        - interface: g1/0/24
          mode: trunk
          native_vlan: 2
          allowed_vlans: [2, 5, 6, 10]
          description: link to 01_edge_router

        - interface: vlan 5
          mode: svi
          address: 10.5.0.1
          mask: 255.255.255.0

    - device: switch
      name: 01_closet_a

      services:





